"""Privacy-bounded persistence for task-center summaries and event logs."""

from __future__ import annotations

import json
import os
import threading
from pathlib import Path
from typing import Any

from config import APP_DATA_DIR


class TaskHistoryStore:
    """Persist only already-sanitized task-center records.

    Runners keep richer in-memory data while producing outputs.  The task
    center never serializes that data directly: callers must provide the
    filtered summary/log payload generated by ``TranslationTaskManager``.
    """

    def __init__(self, path: Path | None = None, *, limit: int = 200) -> None:
        self._path = path or APP_DATA_DIR / "task_history.json"
        self._limit = max(1, int(limit))
        self._lock = threading.RLock()

    def records(self) -> list[dict[str, Any]]:
        with self._lock:
            return self._read_locked()

    def upsert(self, record: dict[str, Any]) -> None:
        task_id = str(record.get("task_id") or "").strip()
        if not task_id:
            return
        with self._lock:
            records = [
                item
                for item in self._read_locked()
                if str(item.get("task_id") or "") != task_id
            ]
            records.insert(0, dict(record))
            self._write_locked(records[: self._limit])

    def mark_active_interrupted(self) -> list[str]:
        """Mark records left active by a prior sidecar as non-resumable."""
        active_states = {"preflight", "running", "paused", "stopping", "finalizing"}
        changed: list[str] = []
        with self._lock:
            records = self._read_locked()
            for item in records:
                if str(item.get("state") or "") not in active_states:
                    continue
                item["state"] = "interrupted"
                item["terminal"] = True
                item["interrupted"] = True
                item["recovery"] = {"can_resume": False, "reason": "sidecar_restarted"}
                item["updated_at"] = _now_epoch()
                changed.append(str(item.get("task_id") or ""))
            if changed:
                self._write_locked(records)
        return changed

    def clear(self) -> int:
        """Remove task-center summaries only; generated outputs are never owned here."""
        with self._lock:
            count = len(self._read_locked())
            self._path.unlink(missing_ok=True)
            self._path.with_suffix(".tmp").unlink(missing_ok=True)
            return count

    def _read_locked(self) -> list[dict[str, Any]]:
        try:
            raw = self._path.read_text(encoding="utf-8")
            data = json.loads(raw)
        except (OSError, ValueError, TypeError):
            return []
        if not isinstance(data, list):
            return []
        return [item for item in data if isinstance(item, dict)]

    def _write_locked(self, records: list[dict[str, Any]]) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self._path.with_suffix(".tmp")
        payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
        temporary.write_text(payload, encoding="utf-8")
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            pass
        temporary.replace(self._path)


def _now_epoch() -> float:
    import time

    return time.time()
