"""Privacy-bounded persistence for task-center summaries and event logs."""

from __future__ import annotations

import json
import os
import threading
import uuid
from pathlib import Path
from typing import Any

import settings as app_settings


_PATH_LOCKS: dict[Path, threading.RLock] = {}
_PATH_LOCKS_GUARD = threading.Lock()
TASK_HISTORY_RECOVERY_SCOPE = "task_history"


class TaskHistoryError(RuntimeError):
    """History cannot be updated without risking the only copy of old data."""


def default_history_path() -> Path:
    """Resolve the history file when a store is created, not at import time.

    Tests isolate app data by patching ``settings.APP_DATA_DIR``.  A path bound
    at import ignores that patch, so fixture tasks end up in the real user data
    directory and then show up as phantom results in the shipped app.
    """
    return Path(app_settings.APP_DATA_DIR) / "task_history.json"


def _lock_for_path(path: Path) -> threading.RLock:
    """Share a lock between stores targeting the same history file."""
    normalized = path.expanduser().resolve()
    with _PATH_LOCKS_GUARD:
        return _PATH_LOCKS.setdefault(normalized, threading.RLock())


class TaskHistoryStore:
    """Persist only already-sanitized task-center records.

    Runners keep richer in-memory data while producing outputs.  The task
    center never serializes that data directly: callers must provide the
    filtered summary/log payload generated by ``TranslationTaskManager``.
    """

    def __init__(self, path: Path | None = None, *, limit: int = 200) -> None:
        self._path = path or default_history_path()
        self._limit = max(1, int(limit))
        self._lock = _lock_for_path(self._path)
        self._blocked_reason = ""

    def records(self) -> list[dict[str, Any]]:
        with self._lock:
            return self._read_locked()

    def upsert(self, record: dict[str, Any]) -> None:
        task_id = str(record.get("task_id") or "").strip()
        if not task_id:
            return
        with self._lock:
            records = [
                item
                for item in self._read_locked()
                if str(item.get("task_id") or "") != task_id
            ]
            records.insert(0, dict(record))
            self._ensure_writable()
            self._write_locked(records[: self._limit])

    def remove(self, task_id: str) -> bool:
        """Drop one record in a single locked read-filter-write.

        Deleting used to be ``clear()`` followed by one ``upsert()`` per kept
        record: on a full 200-record history that is 201 file rewrites (measured
        at ~0.4s), and for the whole of that window the file holds a partial
        list.  A task finishing meanwhile either lands in the middle of the
        rewrite and gets re-ordered, or is written before the backfill reaches
        its position and is dropped outright.
        """
        wanted = str(task_id or "").strip()
        if not wanted:
            return False
        with self._lock:
            records = self._read_locked()
            self._ensure_writable()
            kept = [
                item
                for item in records
                if str(item.get("task_id") or "") != wanted
            ]
            if len(kept) == len(records):
                return False
            self._write_locked(kept)
            return True

    def mark_active_interrupted(self) -> list[str]:
        """Mark records left active by a prior sidecar as non-resumable."""
        active_states = {"preflight", "running", "paused", "stopping", "finalizing"}
        changed: list[str] = []
        with self._lock:
            records = self._read_locked()
            for item in records:
                if str(item.get("state") or "") not in active_states:
                    continue
                item["state"] = "interrupted"
                item["terminal"] = True
                item["interrupted"] = True
                item["recovery"] = {"can_resume": False, "reason": "sidecar_restarted"}
                item["updated_at"] = _now_epoch()
                progress = item.get("file_progress")
                if isinstance(progress, dict):
                    revision = int(progress.get("revision") or 0) + 1
                    for entry in progress.get("files") or []:
                        if isinstance(entry, dict) and entry.get("state") not in {
                            "generated", "failed", "unstarted", "stopped", "interrupted",
                        }:
                            entry.update(state="interrupted", revision=revision)
                    progress["revision"] = revision
                changed.append(str(item.get("task_id") or ""))
            if changed:
                self._write_locked(records)
        return changed

    def clear(self) -> int:
        """Remove task-center summaries only; generated outputs are never owned here."""
        with self._lock:
            # Explicit deletion must not create a fresh backup or recovery event.
            try:
                data = json.loads(self._path.read_bytes())
                count = len(data) if isinstance(data, list) else 0
            except (OSError, ValueError):
                count = 0
            self._path.unlink(missing_ok=True)
            for stray in self._stray_temp_paths():
                stray.unlink(missing_ok=True)
            self._blocked_reason = ""
            app_settings.clear_recovery_record([TASK_HISTORY_RECOVERY_SCOPE])
            return count

    def _stray_temp_paths(self) -> list[Path]:
        """Temp files a crash could leave behind mid-``_write_locked``.

        Must match the exact naming ``_write_locked`` uses (hidden dot prefix,
        a random uuid, ``.tmp`` suffix) — ``self._path.with_suffix(".tmp")``
        used to be tried here instead, which never matches that pattern and so
        never actually removed anything.
        """
        return list(self._path.parent.glob(f".{self._path.name}.*.tmp"))

    def _read_locked(self) -> list[dict[str, Any]]:
        self._blocked_reason = ""
        try:
            raw = self._path.read_bytes()
        except FileNotFoundError:
            return []
        except OSError as exc:
            self._blocked_reason = f"任务历史无法读取，新的任务历史暂时无法保存，原文件未被覆盖：{exc}"
            return []
        try:
            data = json.loads(raw)
        except (ValueError, UnicodeError):
            data = None
        kept = [item for item in data if isinstance(item, dict)] if isinstance(data, list) else []
        normalized = []
        progress_repaired = False
        for item in kept:
            progress = item.get("file_progress")
            if isinstance(progress, dict):
                repaired = dict(progress)
                try:
                    int(progress.get("revision") or 0)
                except (TypeError, ValueError, OverflowError):
                    repaired["revision"] = 0
                if progress.get("files") is not None and not isinstance(progress["files"], list):
                    repaired["files"] = []
                if repaired != progress:
                    item = {**item, "file_progress": repaired}
                    progress_repaired = True
            normalized.append(item)
        if isinstance(data, list) and len(kept) == len(data) and not progress_repaired:
            return data
        kept = normalized
        try:
            backup = self._backup_raw_locked(raw)
            self._write_locked(kept)
        except OSError as exc:
            self._blocked_reason = f"任务历史无法安全恢复，备份或写入失败，新的任务历史暂时无法保存，原文件未被覆盖：{exc}"
            return []
        app_settings.record_recovery_event(
            TASK_HISTORY_RECOVERY_SCOPE,
            stored_version=None,
            current_version=1,
            backup_path=str(backup),
        )
        return kept

    def _backup_raw_locked(self, raw: bytes) -> Path:
        directory = self._path.parent / "backups" / TASK_HISTORY_RECOVERY_SCOPE
        directory.mkdir(parents=True, exist_ok=True)
        backup = directory / f"task_history_unusable_{uuid.uuid4().hex}.json"
        # Exclusive creation gives private permissions before any bytes are written.
        descriptor = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            with os.fdopen(descriptor, "wb") as stream:
                private = app_settings.restrict_windows_file_to_owner(backup)
                if os.name == "nt" and not private:
                    raise PermissionError("无法为任务历史备份设置仅当前用户可访问的权限")
                stream.write(raw)
                stream.flush()
                os.fsync(stream.fileno())
        except BaseException:
            backup.unlink(missing_ok=True)
            raise
        return backup

    def _ensure_writable(self) -> None:
        if self._blocked_reason:
            raise TaskHistoryError(self._blocked_reason)

    def health_status(self) -> dict[str, object]:
        with self._lock:
            self._read_locked()
            return {
                "state": "unreadable" if self._blocked_reason else "current",
                "stored_version": None,
                "current_version": 1,
                "reason": self._blocked_reason,
            }

    def _write_locked(self, records: list[dict[str, Any]]) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self._path.with_name(
            f".{self._path.name}.{uuid.uuid4().hex}.tmp"
        )
        payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
        try:
            temporary.write_text(payload, encoding="utf-8")
            try:
                os.chmod(temporary, 0o600)
            except OSError:
                pass
            temporary.replace(self._path)
        finally:
            temporary.unlink(missing_ok=True)


def _now_epoch() -> float:
    import time

    return time.time()
